language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.1

before_script:
  - "export DISPLAY=:99.0"
  - "export RACK_ENV=test" 
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "python manage.py runserver &"
  - sleep 5

script:
  - "python manage.py test main"
