language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.1

before_script:
  - "export DISPLAY=:99.0"
  - "export RACK_ENV=test"
  - secure: "PP1usGHuMo78K42gLsVwELSSwwuVqSO6+k8Rll59Q7e1ksoxcr3MLryaDUIt\nL96M4XxiVgowhrmdUorQuXvcM2xBDeh6qxU/XADdNC4PTLRgGqzwI5okbs/o\nYhKczULe+OfhSG/90vzPa1MYC21XbRk9VqmXtHXTGG1xbguwbP8="
  - secure: "ptexJP10s7rSiuRMR0k+AofoIxxVSp7cq0hbbCGyc4VJh048CWrW8/yDmb1A\nhOG1ww1J/20h8KzL1YO2GfP1mraqRPcmznpvyc5Xg7KI4jV2J+xyeiwRx0Hx\n2gdQvFyUzRLTi2RF/pTVCphOXdzAbg0YUvSCzCXHseoPur95n9k="
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "python manage.py runserver &"
  - sleep 5

script:
  - "python manage.py test main"
